DROP SCHEMA app CASCADE;
DROP SCHEMA app_private CASCADE;

DROP ROLE ANONYMOUS;

DROP ROLE ETUDIANT;

REASSIGN OWNED BY MEDECIN TO postgres;
DROP OWNED BY MEDECIN;
DROP ROLE MEDECIN;

DROP ROLE ENSEIGNANT;
DROP ROLE ATS;
DROP TYPE SEXE;

DROP TYPE SPECIALITE;

DROP TYPE FAMILY_STATUS;

DROP TYPE ROLE;

DROP EXTENSION "uuid-ossp";